export const judges = [
  {
    id: 1,
    name: "Ayushman Sharma",
    designation: "SDE-2",
    company: "Navi Technologies Pvt Limited",
    image: "/judges/ayushman.webp",
    expertise: "Android Development",
    githubLink: "https://github.com/",
    linkedinLink: "https://in.linkedin.com/in/ayushman-sharma-2a9380196",
  },
  {
    id: 2,
    name: "Shreya Rana",
    designation: "Software Engineer III",
    company: "Google",
    image: "/judges/shreya.webp",
    expertise: "AI & Distributed Systems",
    githubLink: "",
    linkedinLink: "https://www.linkedin.com/in/shreya-rana-/",
  },
  {
    id: 3,
    name: "Ganesh Rajan",
    designation: "SDE1",
    company: "Flipkart",
    image: "/judges/ganesh.webp",
    expertise: "Backend Development",
    githubLink: "",
    linkedinLink: "https://www.linkedin.com/in/rajan-ganesh",
  },
  {
    id: 4,
    name: "Arkaza Kumari",
    designation: "Software Development Engineer",
    company: "Microsoft",
    image: "/judges/arkaza.webp",
    expertise: "Full Stack Development",
    githubLink: "https://github.com/arkaza369",
    linkedinLink: "https://www.linkedin.com/in/arkaza-sde/",
  },
  {
    id: 5,
    name: "Ishaan Gupta",
    designation: "GenAI Engineer",
    company: "Hexaware Technologies",
    image: "/judges/ishaan.webp",
    expertise: "Full Stack & GenAI",
    githubLink: "",
    linkedinLink: "https://www.linkedin.com/in/ishaangupta1201",
  },
  {
    id: 6,
    name: "Abhinav Kiran",
    designation: "SDE2",
    company: "Amazon",
    image: "/judges/abhinav.webp",
    expertise: "Software Development",
    githubLink: "",
    linkedinLink: "https://www.linkedin.com/in/abhinavkiran/",
  },
  {
    id: 7,
    name: "Vivek Parida",
    designation: "Software Engineer",
    company: "aroundU",
    image: "/judges/vivek.webp",
    expertise: "App Development, UI/UX",
    githubLink: "NA",
    linkedinLink: "https://www.linkedin.com/in/vivek-parida/",
  },
  {
    id: 8,
    name: "Rishikesh Kale",
    designation: "Developer Advocate",
    company: "FIL-B",
    image: "/judges/kale.webp",
    expertise: "Blockchain Technology",
    githubLink: "https://github.com/rk-rishikesh",
    linkedinLink: "https://www.linkedin.com/in/rishikeshkale",
  }
   

  ];
  const participants = [
    {
      id: 1,
      name: "Ayushman Sharma",
      designation: "SDE-2",
      company: "Navi Technologies Pvt Limited",
      image: "judges/ayushman.webp",
      expertise: "Android Development",
      githubLink: "",
      linkedinLink: "https://in.linkedin.com/in/ayushman-sharma-2a9380196",
    },
    {
      id: 2,
      name: "Shreya Rana",
      designation: "Software Engineer III",
      company: "Google",
      image: "/judges/shreya.webp",
      expertise: "AI & Distributed Systems",
      githubLink: "",
      linkedinLink: "https://www.linkedin.com/in/shreya-rana-/",
    },
    {
      id: 3,
      name: "Ganesh Rajan",
      designation: "SDE1",
      company: "Flipkart",
      image: "/judges/ganesh.webp",
      expertise: "Backend Development",
      githubLink: "",
      linkedinLink: "https://www.linkedin.com/in/rajan-ganesh",
    },
    {
      id: 4,
      name: "Arkaza Kumari",
      designation: "Software Development Engineer",
      company: "Microsoft",
      image: "/judges/arkaza.webp",
      expertise: "Full Stack Development",
      githubLink: "https://github.com/arkaza369",
      linkedinLink: "https://www.linkedin.com/in/arkaza-sde/",
    },
    {
      id: 5,
      name: "Ishaan Gupta",
      designation: "GenAI Engineer",
      company: "Hexaware Technologies",
      image: "/judges/ishaan.webp",
      expertise: "Full Stack & GenAI Development",
      githubLink: "",
      linkedinLink: "https://www.linkedin.com/in/ishaangupta1201",
    },
    {
      id: 6,
      name: "Abhinav Kiran",
      designation: "SDE2",
      company: "Amazon",
      image: "/judges/abhinav.webp",
      expertise: "Software Development",
      githubLink: "",
      linkedinLink: "https://www.linkedin.com/in/abhinavkiran/",
    },
    {
      id: 7,
      name: "Vivek Parida",
      designation: "Software Engineer",
      company: "aroundU",
      image: "/judges/vivek.webp",
      expertise: "App Development, UI/UX",
      githubLink: "NA",
      linkedinLink: "https://www.linkedin.com/in/vivek-parida/",
    },
    {
      id: 8,
      name: "Rishikesh Kale",
      designation: "Developer Advocate",
      company: "FIL-B",
      image: "/judges/kale.webp",
      expertise: "Blockchain Technology",
      githubLink: "https://github.com/rk-rishikesh",
      linkedinLink: "https://www.linkedin.com/in/rishikeshkale",
    }
  ];